#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.EmbeddedViews
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    #line 1 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
    using Geocrest.Web.Mvc.Documentation;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Help/DisplayTemplates/ApiGroup.cshtml")]
    public partial class _ApiGroup : System.Web.Mvc.WebViewPage<IGrouping<string, System.Web.Http.Description.ApiDescription>>
    {
        public _ApiGroup()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h3");

WriteAttribute("id", Tuple.Create(" id=\"", 114), Tuple.Create("\"", 129)
            
            #line 4 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
, Tuple.Create(Tuple.Create("", 119), Tuple.Create<System.Object, System.Int32>(Model.Key
            
            #line default
            #line hidden
, 119), false)
);

WriteLiteral(">");

            
            #line 4 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
               Write(Model.Key);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-condensed table-bordered help-page-table\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr><th>API</th><th>Description</th></tr>\r\n      " +
"  </thead>\r\n        <tbody>\r\n");

            
            #line 11 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
            
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
             foreach (var api in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" class=\"api-name\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                          
                var label = string.Format("{0} {1}", api.HttpMethod.Method, (api.RelativePath.Contains("?") ?
                        api.RelativePath.Substring(0, api.RelativePath.IndexOf("?")) :
                        api.RelativePath));
                if (api.Route.Defaults.ContainsKey("area"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"help\"");

WriteAttribute("href", Tuple.Create(" href=\"", 869), Tuple.Create("\"", 1184)
            
            #line 21 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
, Tuple.Create(Tuple.Create("", 876), Tuple.Create<System.Object, System.Int32>(Url.Action("api", "help", new
                                 {
                                    id =  api.Route.Defaults["area"].ToString().ToLower(),
                                    apiId = api.GetFriendlyId(),
                                    area = ""
                                 })
            
            #line default
            #line hidden
, 876), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                   Write(label);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n");

            
            #line 29 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"help\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1341), Tuple.Create("\"", 1562)
            
            #line 32 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
, Tuple.Create(Tuple.Create("", 1348), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "help", new
                                {
                                   apiId = api.GetFriendlyId(),
                                   area = ""
                                })
            
            #line default
            #line hidden
, 1348), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 37 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                   Write(label);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n");

            
            #line 39 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"api-documentation\"");

WriteLiteral(">\r\n");

            
            #line 43 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                         if (api.Documentation != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p>");

            
            #line 45 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                          Write(MvcHtmlString.Create(api.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 46 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p>No documentation available.</p>\r\n");

            
            #line 50 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");

            
            #line 53 "..\..\Views\Help\DisplayTemplates\ApiGroup.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
