#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.EmbeddedViews
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
    using System.Collections.ObjectModel;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 3 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
    using System.Web.Http.Description;
    
    #line default
    #line hidden
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Help/DisplayTemplates/Parameters.cshtml")]
    public partial class Parameters_ : System.Web.Mvc.WebViewPage<Collection<System.Web.Http.Description.ApiParameterDescription>>
    {
        public Parameters_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-bordered table-condensed help-page-table\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr><th>Name</th><th>Description</th><th>Addition" +
"al information</th></tr>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 12 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
             foreach (var parameter in Model)
            {
                string parameterDocumentation = parameter.Documentation != null ?
                    parameter.Documentation :
                    "No documentation available.";

                // Don't show CancellationToken because it's a special parameter
                if (!typeof(CancellationToken).IsAssignableFrom(parameter.ParameterDescriptor.ParameterType))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td");

WriteLiteral(" class=\"parameter-name\"");

WriteLiteral("><code>");

            
            #line 22 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                                    Write(parameter.Name);

            
            #line default
            #line hidden
WriteLiteral("</code></td>\r\n                        <td");

WriteLiteral(" class=\"parameter-documentation\"");

WriteLiteral("><p>");

            
            #line 23 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                                          Write(MvcHtmlString.Create(parameterDocumentation));

            
            #line default
            #line hidden
WriteLiteral("</p></td>\r\n                        <td");

WriteLiteral(" class=\"parameter-source\"");

WriteLiteral(">\r\n                            <p>\r\n                                <strong>");

            
            #line 26 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                    Write(parameter.ParameterDescriptor.IsOptional ? "Optional" : "Required");

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n");

            
            #line 27 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                 switch (parameter.Source)
                                {
                                    case ApiParameterSource.FromBody:

            
            #line default
            #line hidden
WriteLiteral("                                        ");

WriteLiteral("Define this parameter in the request <strong>body</strong>.\r\n");

            
            #line 31 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                break;
                                    case ApiParameterSource.FromUri:

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral("Define this parameter in the request <strong>URI</strong>");

            
            #line 33 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                                                                           Write(parameter.ParameterDescriptor
                                .IsOptional ? " using the query string" : "");

            
            #line default
            #line hidden
WriteLiteral(".\r\n");

            
            #line 35 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                break;
                                    case ApiParameterSource.Unknown:
                                    default:

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral("No additional information.\r\n");

            
            #line 39 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                break;
                                }

            
            #line default
            #line hidden
WriteLiteral("                                ");

            
            #line 41 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                 if (parameter.ParameterDescriptor.IsOptional)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <em>The default is \'");

            
            #line 43 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                                   Write(parameter.ParameterDescriptor.DefaultValue);

            
            #line default
            #line hidden
WriteLiteral("\'.</em>\r\n");

            
            #line 44 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </p>\r\n                        </td>\r\n                " +
"    </tr>\r\n");

            
            #line 48 "..\..\Views\Help\DisplayTemplates\Parameters.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
