#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePasswordSuccess.cshtml")]
    public partial class ChangePasswordSuccess : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ChangePasswordSuccess()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ChangePasswordSuccess.cshtml"
  
    ViewBag.Title = BaseApplication.ApplicationTitle + " | Change Password";

            
            #line default
            #line hidden
WriteLiteral("\r\n<section");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row text-center\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-6 col-sm-offset-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                    <h2>Your password has been changed.</h2>\r\n                " +
"</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>");

        }
    }
}
#pragma warning restore 1591
