#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 5 "..\..\Forms.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Forms.cshtml"
    using System.Linq.Expressions;
    
    #line default
    #line hidden
    using System.Net;
    
    #line 6 "..\..\Forms.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Forms.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 3 "..\..\Forms.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class Forms
    {
        
        #line 8 "..\..\Forms.cshtml"
       
    public static HelperResult TextBox<TModel, TItem>(HtmlHelper<TModel> html, Expression<Func<TModel, TItem>> expr, object htmlAttributes = null)
    {
        return Editor(html.LabelFor(expr, new { @class = "col-sm-4 control-label" }), html.TextBoxFor(expr, htmlAttributes),
            html.ValidationMessageFor(expr), 3);
    }
    public static string TokenHeaderValue()
    {
        string cookieToken, formToken;
        AntiForgery.GetTokens(null, out cookieToken, out formToken);
        return cookieToken + ":" + formToken;
    }

        #line default
        #line hidden

public static System.Web.WebPages.HelperResult Editor(MvcHtmlString label, MvcHtmlString editor, MvcHtmlString validation, int bootstrapVersion)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 22 "..\..\Forms.cshtml"
 
    if (bootstrapVersion == 3)
    { 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"form-group\">\r\n        ");



#line 26 "..\..\Forms.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, label);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        <div class=\"col-sm-8\">\r\n            ");



#line 28 "..\..\Forms.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, editor);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n            ");



#line 29 "..\..\Forms.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, validation);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        </div>\r\n    </div>   \r\n");



#line 32 "..\..\Forms.cshtml"
    }
    else
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"control-group\">\r\n        ");



#line 36 "..\..\Forms.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, label);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        <div class=\"controls\">\r\n            ");



#line 38 "..\..\Forms.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, editor);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n            ");



#line 39 "..\..\Forms.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, validation);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        </div>\r\n    </div>\r\n");



#line 42 "..\..\Forms.cshtml"
    }    

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
