#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.EmbeddedViews
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    #line 1 "..\..\Views\Help\Api.cshtml"
    using Geocrest.Web.Mvc.Documentation;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Help/Api.cshtml")]
    public partial class Api : System.Web.Mvc.WebViewPage<Geocrest.Web.Mvc.Documentation.HelpPageApiModel>
    {
        public Api()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Help\Api.cshtml"
  
    var description = Model.ApiDescription;
    ViewBag.Title = ("Documentation " + (!string.IsNullOrEmpty(ViewBag.Version) ?
        "(v" + ViewBag.Version + ") - " : " - ") + (description.RelativePath.Contains("?") ?
        description.RelativePath.Substring(0, description.RelativePath.IndexOf("?")).ToLower() :
        description.RelativePath.ToLower()));
    string css = "Geocrest.Web.Mvc.Documentation.HelpPage.css";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Help\Api.cshtml"
Write(Html.CssLink(css));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <p>\r\n");

            
            #line 18 "..\..\Views\Help\Api.cshtml"
                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Help\Api.cshtml"
                  
                    if (!string.IsNullOrEmpty(Model.HomePageUrl))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"pop\"");

WriteAttribute("href", Tuple.Create(" href=\"", 804), Tuple.Create("\"", 829)
            
            #line 21 "..\..\Views\Help\Api.cshtml"
, Tuple.Create(Tuple.Create("", 811), Tuple.Create<System.Object, System.Int32>(Model.HomePageUrl
            
            #line default
            #line hidden
, 811), false)
);

WriteLiteral(">Help Page Home</a>\r\n");

            
            #line 22 "..\..\Views\Help\Api.cshtml"
                    }
                    else if (!string.IsNullOrEmpty(ViewBag.Area.ToLower()))
                    {
                        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Help\Api.cshtml"
                   Write(Html.ActionLink("Help Page Home", "api", "help", new
                        {
                            area = "",
                            id = ViewBag.Area.ToLower(),
                            apiId = ""
                        }, new { @class = "pop" }));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Help\Api.cshtml"
                                                  
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Help\Api.cshtml"
                   Write(Html.ActionLink("Help Page Home", "index", "help", new
                        {
                            area = "",
                            api = ""
                        }));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Help\Api.cshtml"
                          

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"pop\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1594), Tuple.Create("\"", 1623)
            
            #line 39 "..\..\Views\Help\Api.cshtml"
, Tuple.Create(Tuple.Create("", 1601), Tuple.Create<System.Object, System.Int32>(Url.Content("~/help")
            
            #line default
            #line hidden
, 1601), false)
);

WriteLiteral(">Help Page Home</a>\r\n");

            
            #line 40 "..\..\Views\Help\Api.cshtml"
                    }
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

            
            #line 46 "..\..\Views\Help\Api.cshtml"
Write(Html.DisplayFor(m => Model));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
