#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.Views.Feedback
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Feedback/_ContactForm.cshtml")]
    public partial class ContactForm : System.Web.Mvc.WebViewPage<Geocrest.Web.Mvc.Models.Feedback>
    {
        public ContactForm()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 6 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.LabelFor(x => x.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.TextBoxFor(x => x.Name, new { placeholder = "Full Name", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.ValidationMessageFor(x => x.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.LabelFor(x => x.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.TextBoxFor(x => x.Email, new { placeholder = "Email Address", @class = "form-control", type="email" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.ValidationMessageFor(x => x.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.LabelFor(x =>x.FeedbackSubjectId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.DropDownListFor(model => model.FeedbackSubjectId, ((IEnumerable<Geocrest.Web.Mvc.Models.FeedbackSubject>)ViewBag.FeedbackSubjects)
            .Select(x => new System.Web.Mvc.SelectListItem
            {
                Text = x.Subject,
                Value = x.Id.ToString()
            }),"Choose a subject...", new { @class = "form-control" }
        ));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 23 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.ValidationMessageFor(model => model.FeedbackSubjectId));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 26 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.LabelFor(x => x.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.TextAreaFor(x => x.Comment, new { placeholder = "Your Message", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Feedback\_ContactForm.cshtml"
Write(Html.ValidationMessageFor(x => x.Comment));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <button");

WriteLiteral(" class=\"btn btn-lg submit btn-block\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"submitFeedback\"");

WriteLiteral("\r\n            data-loading-text=\"\r\n        <i class=\'fa fa-spinner fa-spin\'></i>&" +
"nbsp;Submitting...\"");

WriteLiteral("\r\n        >Submit\r\n    </button>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
