#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.Views.Feedback
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Feedback/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<Geocrest.Web.Mvc.Models.Feedback>
    {
        public Create()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Feedback\Create.cshtml"
 using (Ajax.BeginForm("create", "feedback", new { area = "" }, new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "resetForm(data)",
            OnFailure = "onFailure(xhr,status,error,'#ajaxresult','#submitFeedback')",
            OnBegin = "onBegin(xhr, '#ajaxresult','#submitFeedback')",
            OnComplete = "onComplete"
        }, new { @class = "contact-form well", id = "contactForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Feedback\Create.cshtml"
Write(Html.Partial("_contactform"));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Feedback\Create.cshtml"
                                 
}

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    function resetForm(data) {\r\n        var form = $(\'#feedbackForm\');\r\n      " +
"  if (form.length > 0) {\r\n            $(form).load(\'");

            
            #line 18 "..\..\Views\Feedback\Create.cshtml"
                     Write(Url.Action("create", "feedback", new { area = "" }));

            
            #line default
            #line hidden
WriteLiteral(@"', function () {
                $(""#contactForm"").each(function () { $.data($(this)[0], 'validator', false); });
                $.validator.unobtrusive.parse(""#contactForm"");
            });
        }
        onSuccess(data, '#feedbacklist', '#ajaxresult', '', '#submitFeedback');
    }
</script>
");

        }
    }
}
#pragma warning restore 1591
