#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.Views.Feedback
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Feedback/List.cshtml")]
    public partial class List : System.Web.Mvc.WebViewPage<IEnumerable<Geocrest.Web.Mvc.Models.Feedback>>
    {
        public List()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Feedback\List.cshtml"
 foreach (var item in Model)
{

            
            #line default
            #line hidden
WriteLiteral("    <blockquote");

WriteAttribute("id", Tuple.Create(" id=\"", 104), Tuple.Create("\"", 149)
            
            #line 5 "..\..\Views\Feedback\List.cshtml"
, Tuple.Create(Tuple.Create("", 109), Tuple.Create<System.Object, System.Int32>(string.Format("feedback-{0}", @item.Id)
            
            #line default
            #line hidden
, 109), false)
);

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n        <strong>");

            
            #line 6 "..\..\Views\Feedback\List.cshtml"
           Write(item.FeedbackSubject.Subject);

            
            #line default
            #line hidden
WriteLiteral("</strong> - ");

            
            #line 6 "..\..\Views\Feedback\List.cshtml"
                                                    Write(item.Comment);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <small><strong>");

            
            #line 7 "..\..\Views\Feedback\List.cshtml"
                  Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong> - <a");

WriteLiteral(" href=\"mailto:#\"");

WriteLiteral(">");

            
            #line 7 "..\..\Views\Feedback\List.cshtml"
                                                           Write(item.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></small><br />\r\n        <small><strong>Published: </strong>");

            
            #line 8 "..\..\Views\Feedback\List.cshtml"
                                      Write(item.PublishDate);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n");

            
            #line 9 "..\..\Views\Feedback\List.cshtml"
        
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Feedback\List.cshtml"
         using (Ajax.BeginForm("delete", "feedback", new { area = "" }, new AjaxOptions
        {
            HttpMethod = "DELETE",
            Confirm = "Delete comment? Are you sure",
            OnSuccess = "onDelete(data, '#feedback-' + data.id, '#ajaxresult')",
            OnFailure = "onFailure(xhr,status,error,'#ajaxresult')",
            OnBegin = "onBegin(xhr, '#ajaxresult')",
            OnComplete = "onComplete"
        }))
        {
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Feedback\List.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Feedback\List.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Feedback\List.cshtml"
       Write(Html.Hidden("Id", @item.Id));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Feedback\List.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger pull-right\"");

WriteLiteral(">Delete comment</button>\r\n");

            
            #line 22 "..\..\Views\Feedback\List.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </blockquote>\r\n");

            
            #line 24 "..\..\Views\Feedback\List.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
