#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocrest.Web.Mvc.Views.Feedback
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Geocrest.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Feedback/Testimonials.cshtml")]
    public partial class Testimonials : System.Web.Mvc.WebViewPage<IEnumerable<Geocrest.Web.Mvc.Models.Feedback>>
    {
        public Testimonials()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Feedback\Testimonials.cshtml"
  
    var i = 0;    

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Feedback\Testimonials.cshtml"
 foreach (var item in Model)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 122), Tuple.Create("\"", 172)
, Tuple.Create(Tuple.Create("", 130), Tuple.Create("testimonial", 130), true)
, Tuple.Create(Tuple.Create(" ", 141), Tuple.Create("item", 142), true)
            
            #line 7 "..\..\Views\Feedback\Testimonials.cshtml"
, Tuple.Create(Tuple.Create(" ", 146), Tuple.Create<System.Object, System.Int32>(i == 0 ? "active" : ""
            
            #line default
            #line hidden
, 147), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"comment\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Feedback\Testimonials.cshtml"
                            Write(item.Comment);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"author\"");

WriteLiteral("><strong>");

            
            #line 10 "..\..\Views\Feedback\Testimonials.cshtml"
                                   Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong></div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 13 "..\..\Views\Feedback\Testimonials.cshtml"
    i++;
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
